name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  call-response:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: RESPONSE - Dispatch response to received call
        if: github.event.action == 'call'
        run: |
          curl -X POST https://api.github.com/repos/RoadieHQ/backstage-plugin-github-insights/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "response", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'