name: Remote Dispatch Action Responder
 
on: 
  push:
 
jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Event Information
        run: |
         echo "Event '${{ github.event.client_payload.repository }}' received from '${{ github.event.client_payload.repository }}'"