name: Remote Dispatch Action Responder
 
on: 
  push:
  repository_dispatch:
 
jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' and branch name is '${{ github.event.client_payload.ref }}'"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout branch in submodule
        uses: textbook/git-checkout-submodule-action@'${{ github.event.client_payload.ref }}'
      - name: Checkout submodules
        run: git submodule update --init --recursive