name: Remote Dispatch Action Responder
 
on: 
  push:
  repository_dispatch:
 
jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' and commit sha is '${{ github.event.client_payload.sha }}'"
        if: github.event.action == 'call'
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'true'
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive    
          cd plugins/${{ github.event.client_payload.repository }}
          git fetch --all
          git show
          git checkout ${{github.event.client_payload.sha}}
          yarn run test:e2e-docker
      - run: |
          curl -X POST https://api.github.com/repos/RoadieHQ/${{ github.event.client_payload.repository }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "response", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'