name: Remote Dispatch Action Responder
 
on: 
  push:
  repository_dispatch:
 
jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' and commit sha is '${{ github.event.client_payload.sha }}'"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'true'
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive    
          cd plugins/backstage-plugin-github-insights
          git fetch --all
          git branch -a
          git remote -v
          git log