name: Remote Dispatch Action Responder
 
on: 
  push:
 
jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout submodules
        uses: plugins-verification/git-checkout-submodule-action@master
      - uses: actions/checkout@$v2
        with:
          path: plugins/${{ github.event.client_payload.repository }}
      - name: Event Information
        run: |
          echo "Event '${{ github.event.check_suite[head_branch] }}' received from '${{ github.event.client_payload.repository }}'"