name: Remote Dispatch Action Responder
 
on: 
  push:
  repository_dispatch:
 
jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' and commit sha is '${{ github.event.client_payload.sha }}'"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout submodules
        run: git submodule update --init --recursive    
      - run: cd plugins/backstage-plugin-github-insights
      - name: Fetch branches
        run: git fetch --all
      - run: git checkout origin/${{github.event.client_payload.branch}}
      - name: Checkout commit in submodule
        run: git checkout ${{github.event.client_payload.sha}}
   